### ISSUE TITLE
Invalid Merged Channel State When Logged in to Two Teams in Same Browser

### ISSUE THREAD

**Issue by blaskovicz** [mattermost/platform#1052]
If i'm logged into the _town-hall_ channel of a team (say _team-a_), and then, in a separate tab, I log into _team-b_ and go to the _town-hall_ channel, if I switch back to the _team-a_ tab, the channel list will be updated to reflect _team-b_'s channel, whilst still showing the old url/team-name. Along with this, on the first tab (_team-a_) the current channel will start getting populated with messages from the currently logged in team/channel (_team-b/town-hall_). 

Upon refresh of the _team-a/town-hall_ tab, the url will remain the same, but the actual other data (team name, color them, etc) will reflect those of the other tab (_team-b_).

**Comment by it33** [comment]
Hi @blaskovicz, appreciate the report. This should be fixed now in Mattermost v1.1 [available now for download](http://www.mattermost.org/download/)

**Comment by blaskovicz** [comment]
Hey, @it33, just as a side note, I'd like to report that the link to the [production install on Ubuntu](https://github.com/mattermost/platform/blob/master/doc/install/Production-Ubuntu.md) still shows `$ wget .. v1.0.0`

**Comment by it33** [comment]
Oops, fixed the install guide now, highly appreciated!

It looks like your issue might not have been completely fixed in v1.1, we're investigating now and need to come back on this,

**Comment by blaskovicz** [comment]
So, this seems to be partially fixed in `v1.1.0`. I notice two distinct differences:

1) now, instead of receiving merged state in the old tab, the message fails to send.
2) when I refresh the page on the old tab (`f5`) the url updates to the currently logged in teams

Although these two points are improvements, I still see it as a bit confusing for the user experience since there's no indicator why the message is failing to send or why I'm automatically redirected to another team.

**Comment by coreyhulen** [comment]
A pull request has been submitted https://github.com/mattermost/platform/pull/1129

**Comment by coreyhulen** [comment]
This is now in master.
