### ISSUE TITLE
Bug: "replies" to incoming webhook messages with username overridden show the original username.

### ISSUE THREAD

**Issue by tmuka** [mattermost/platform#1622]
"replies" to incoming webhook messages with username overridden show the original username eg
![image](https://cloud.githubusercontent.com/assets/338934/11595050/75bc713c-9a7b-11e5-952c-36be252ee6e1.png)
![image](https://cloud.githubusercontent.com/assets/338934/11595041/6a5bb078-9a7b-11e5-9254-9e62b4a2625e.png)

"Commented on tony's message" should say "Commented on webint's message".

similar to this fixed related issue we used to notice for notifications https://github.com/mattermost/platform/pull/1236
hopefully the fix for this is similarly easy! thanks!

edit: we're running the latest version from ubuntu package manager...
Mattermost 1.2.1
Build Number:4063
Build Date:Mon Nov 16 16:56:43 UTC 2015

**Comment by it33** [comment]
I think this is fixed, adding @esethna to confirm and also double check as part of v1.3 testing

**Comment by esethna** [comment]
@tmuka thanks for pointing this out. This is not yet fixed on master but I have filed a bug ticket [here](https://mattermost.atlassian.net/browse/PLT-1399)

**Comment by tmuka** [comment]
excellent, glad to help! thank you :)
