### ISSUE TITLE
"Show more messages" occasionally misses some messages.

### ISSUE THREAD

**Issue by npcode** [mattermost/platform#1906]
When I clicked "Show more messages" link in my private channel today, it showed only two messages for the past two days even if actually there were hundreds of messages.

**Comment by npcode** [comment]
I can find the missed messages by searching and jump to them.

**Comment by lfbrock** [comment]
We think we may have found this issue, if you notice this again can you check the browser and server error logs and let us know if you see anything?

**Comment by npcode** [comment]
@lfbrock This occurs always for me and there is no error in server and browser.

**Comment by lfbrock** [comment]
Can you repro this on a clean system? We're having trouble reproducing it on ours.

**Comment by npcode** [comment]
@lfbrock It is not easy to reproduce in a clean system. This occurs only in a specific private group.

**Comment by Ticki** [comment]
Dup of https://github.com/mattermost/platform/issues/1928?

**Comment by it33** [comment]
Hi @npcode, this should have been fixed in 2.0. It was very hard to reproduce so we didn't end up with a ticket for it, but @jwilander had investigated it closely and found the underlying issue (not sure the precise commit, we did discuss this during the release meetings). 

Closing this for now and if anyone finds it again, please open a new ticket. 

Highly appreciate the report, it was very difficult to uncover, but we're extremely glad we found it.

**Comment by npcode** [comment]
I still have this problem with mattermost 2.1. When I enter a private group, some messages disappear occasionally. (In this time, I didn't need to click "Load more messages" to produce this problem)
