### ISSUE TITLE
"Send Push Notifications:" flag in System Console can't be set to "true" / reverts to false after saving

### ISSUE THREAD

**Issue by finius** [mattermost/platform#1908]
I tried to set the "Push Notification Server" flag and to enable the "Send Push Notifications" flag (set it to "true"), because Mattermost tells all the time that it's unavailable even though it is published through firewall using our external URL. The settings seem to save, however, when I reload the page, it's again set to "false". Unfortunately the size doesn't provide any hint why saving of the settings is unsuccesful.

**Comment by lfbrock** [comment]
This should be fixed in v1.4.

**Comment by finius** [comment]
Unfortunately, in fact it's not. Same with "Enable Team Creation" - it always reverts to defaults. Even after a system reboot

**Comment by finius** [comment]
Indeed I had already been using 1.4, however the problem persisted anyway. 
Maybe the update from 1.3 didn't solved the problem properly. I reinstalled the server now - the fresh server had no such issue again, so the case may be kept closed.
