### ISSUE TITLE
Webhooks sent to a channel user is not a member of cause error

### ISSUE THREAD

**Issue by mcfedr** [mattermost/platform#3021]
#### Summary

Webhooks sent to a channel user is not a member of cause error to be shown and notification to be shown.

#### Steps to reproduce

1. Create a webhook, send to it with `{channel: '#some-channel-im-not-a-member-of'}`
2. See error in mattermost client 'We couldn't get the channel member'
3. Error in log

    [2016/05/17 11:46:03 UTC] [EROR] /api/v1/channels/XXXX/:SqlChannelStore.GetMember code=500 rid=XXX uid=XXX ip=X.X.X.X We couldn't get the channel member [details: channel_id=XXXuser_id=XXX,sql: no rows in result set]
4. Receive a loud notification

#### Expected behavior

The message should be sent to the channel, even if im not a member, and see that i'm not a member, and so not notify me about it

#### Related Issues

Maybe related to https://github.com/mattermost/platform/issues/2928

**Comment by lfbrock** [comment]
Hi @mcfedr, what version of Mattermost are you running?

I just tried to reproduce this on master, and it seemed to work fine for public channels I was not a part of, and for direct message channels that had not been created yet.

**Comment by mcfedr** [comment]
I am using 2.2.0, bundled with GitLab. If this is already fixed in a newer version, sorry for the extra issue :) Ill look forward to GitLab updating the bundled version...

**Comment by lfbrock** [comment]
No worries! It seems to be working for me, so I'll close this issue and you can reopen it if there's still issues after the v3.0 upgrade.

**Comment by aconite33** [comment]
This is still an issue post 3.1 Mattermost. Requires to have a window open.

**Comment by lfbrock** [comment]
Hi @aconite33, can you clarify the repro steps? What do you mean it requires a direct message to be open?
