### ISSUE TITLE
Links are opened inside Android client's webview

### ISSUE THREAD

**Issue by Rudloff** [mattermost/platform#3036]
#### Summary
When I click on a link inside a message on the Android app, it opens the page inside the application webview. It is then hard to get back to the conversation.

#### Steps to reproduce
1. Login to a team
1. Post a message with a link inside
1. Click on the link

#### Expected behavior
It should open the link in the browser.

#### Observed behavior
The link is opened directly in the application.

**Comment by lfbrock** [comment]
Hi @Rudloff, can you check what version of the Android app you're on?

I think it might be fixed in v3.0 of Android app, you can find it here: https://github.com/mattermost/android/releases

**Comment by Rudloff** [comment]
I am using 2.1 from Play Store.
I tried 3.0 but I get a very strange behavior : as soon as I open the app, it opens my team in my Firefox browser.

**Comment by lfbrock** [comment]
Hi @Rudloff - if you're using GitLab sign in, I think we just fixed the issue with it opening in a browser in this release https://github.com/mattermost/android/releases/tag/v3.0.6.

You may need to upgrade Mattermost to v3.0 for the app to work properly if you haven't already done that.

**Comment by Rudloff** [comment]
I'm not using Gitlab sign in and I can still reproduce this behavior on 3.0.6.
I'm using the Mattermost instance on https://framateam.org/ so I can't upgrade it myself. I think it uses version 2.2.0.

**Comment by lfbrock** [comment]
Oh I see, you probably need to wait for the server to update to v3.0 as well for it to work. I think the new Android app only works with the v3.0 server, which is probably why it's opening in the web view. 

(You can also find older versions of the Android app on our [releases page](https://github.com/mattermost/android/releases) if needed). 

In the meantime I'm going to close this issue since I think it's been fixed in the new version, but if you see if happening on v3.0 please re-open it.
