### ISSUE TITLE
File Preview in Upload File Dialogue on Mac OS Cannot Close

### ISSUE THREAD

**Issue by jacob-lee** [mattermost/platform#5795]
#### Summary
On Mac OS 10.11.6, Mattermost 3.5.0, when using the file upload dialog, opting to preview a file causes the preview window to appear, but once loaded, it cannot be closed cancelling upload entirely. Subsequently, Mattermost tends to quit unexpectedly.

#### Steps to reproduce
Open the file upload dialogue, select a file, right-click Quick Look.

#### Expected behavior
Expected behavior is that clicking the close button icon, closes the Quick Look dialogue.

#### Observed behavior
Unable to close, except by cancelling upload. Subsequently, Mattermost tends to crash.

**Comment by jasonblais** [comment]
Thanks @jacob-lee -- which browser is this reproducing?

**Comment by jacob-lee** [comment]
Was using the desktop client on mac.

**Comment by jasonblais** [comment]
Ah, got it -- which Mattermost desktop version are you using (you can find it from Help > Version on the client menu bar).

If it's not the latest (Desktop App v3.6), I recommend downloading the latest as the issue may have been fixed.

**Comment by jacob-lee** [comment]
The app version I was using was 3.5 (as indicated in my ticket). I have since downloaded the latest release of the Mac desktop app. The problem persists: I cannot close the file preview window by clicking the x button. I can only close it by cancelling the upload. Shortly thereafter, Mattermost crashes.

Thanks!

**Comment by jasonblais** [comment]
Thanks! 

And sorry, I thought 3.5 was referring to the server version.

I've opened a ticket in the desktop repo to track: https://github.com/mattermost/desktop/issues/498
