### ISSUE TITLE
Mattermost changes username after upgrading Gitlab to 9.1 and Mattermost Gitlab to 3.7.3

### ISSUE THREAD

**Issue by aitzubi** [mattermost/platform#6207]
#### Summary
Gitlab Onmibus installation. Upgraded from 8.17 to 9.1. No issues. Everything works perfectly.
Upgraded Mattermost from Gitlab Onmibus 8.17.5 to 9.1 (Mattermost 3.7.3).

Mattermost is configured to allow Gitlab SSO login only, no other authentication allowed. Gitlab is configured to allow only ldap login.

After performing the upgrade, I can normally log in into my mattermost teams but my username is modified to some alphanumeric code.

Everything runs on different Centos 7 servers and an external Postgresql 9.6.1 database server.

I checked the postgres database and I can confirm that the username field has changed and that is not a visual glitch on the interface.

The only error I got in the process was when trying to upgrade mattermost gitlab server. The installer (Yum) displays an error where it tells me that it cannot upgrade postgres because it cannot find the server. It was weird because I have the skip_auto_migrations file created.

I changed the username manually using pgadmin but it changes again whenever I login the platform. The field gets updated as well in the database.

As gitlab uses the v4 api on version 9.1, i updated this value on mattermost configuration:

From: `"http://gitlab.example.com/api/v3/user"`
To: `"http://gitlab.example.com/api/v4/user"`

Same result :(

I attach an image so you can see what I am trying to explain here.

#### Steps to reproduce
Centos 7 with external postgresql database 9.6.1 running on a Centos 7 machine as well.

Upgrade Gitlab onmibus 8.17.5 to 9.1 using yum.

Run gitlab-ctl reconfigure.

Log in to mattermost using Gitlab SSO.

#### Expected behavior
Not modify or update the username and showing the correct username.

#### Observed behavior
The username gets modified in the process. It shows an alphanumeric value instead of the username. The username value of the username field is also changed in the database users table.

![mattermost](https://cloud.githubusercontent.com/assets/27918808/25313989/ac20e4ee-283a-11e7-90c9-23179f98958e.jpg)
![mattermost2](https://cloud.githubusercontent.com/assets/27918808/25313990/ac213584-283a-11e7-8a5e-52ce46eec158.jpg)

**Comment by grundleborg** [comment]
Hi @aitzubi this kind of problem typically happens when the gitlab username contains special characters that Mattermost does not support in usernames. There were some changes in 3.7 to the code for validating this, which may explain why this has happened only when you made this upgrade. Could you please tell me what your gitlab username is, so I can better understand what's happening?

**Comment by aitzubi** [comment]
Hi @grundleborg!!

My username is numeric (112233). Six digits to be precise.

As I stated, its a ldap username.

Maybe it is related or not but this upgrade to gitlab 9.1 also broke the ability to sign-in to new users that have never logged in to gitlab. Here is the issue: `https://gitlab.com/gitlab-org/gitlab-ce/issues/31294`

Thanks!

**Comment by it33** [comment]
Seems like a GitLab 9.1 issue, not a Mattermost issue? 

We can track here and close when GitLab releases a patch. Thanks @aitzubi for the report

https://gitlab.com/gitlab-org/gitlab-ce/issues/31294

**Comment by aitzubi** [comment]
@it33 I think that the next patch for gitlab could include the fix. I will keep track as well and we will see if this is fixed as well.

Thanks!

**Comment by aitzubi** [comment]
@it33 we have just upgraded our gitlab installation to 9.1.1 to fix this but the issue still occurs. My username is not showing correctly in mattermost.

I can provide any logs if needed.

**Comment by grundleborg** [comment]
@aitzubi to clarify, the original issue you reported is an issue with Mattermost, which is fixed in version 3.7.4, so when a patch release for Gitlab omnibus ships that includes that version or newer of Mattermost, the issue should go away.

The Gitlab ticket you mentioned is a separate problem that does not relate to Mattermost.

**Comment by lindy65** [comment]
Thanks everyone, I'm closing this issue off here for now as there is [an issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/31294) filed with GitLab.

**Comment by aitzubi** [comment]
@grundleborg This issue still happens after upgrading to 3.7.5.

If the username in Gitlab is numeric, it will not show correctly on mattermost.

We fixed the issue modifying all our usernames to characters but the issue still persist and it has nothing to do with the ldap issue you pointed in gitlab.com.

@lindy65 maybe you should reopen this issue.

Thanks!

**Comment by jasonblais** [comment]
@aitzubi Can you give an example of a username that's causing the issue?

**Comment by aitzubi** [comment]
103215 for example

Thanks @jasonblais

**Comment by grundleborg** [comment]
@jwilander any idea what's up here?

The example is of a user with username `103215` coming from Gitlab authentication. On Mattermost 3.7.3 this was broken and showed a 26 char ID instead of the username in the Mattermost UI. That was expected due to the change we introduced there, but it is still the case after updating to 3.7.5, which I don't think is expected, as I thought we fixed that issue by reverting to the old behaviour in this case.

**Comment by jasonblais** [comment]
@grundleborg @aitzubi  It looks like this wasn't reverted in 3.7.X. 

The fix was submitted to 3.8.1 only, so the issue will be resolved in GitLab v9.2 and later. GitLab 9.2 will release on May 22.

**Comment by lindy65** [comment]
Hi @aitzubi,

Can you let us know whether your issue is resolved now that GitLab 9.2 has been released?

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to GtiLab 9.2.

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
