### ISSUE TITLE
JS errors when switching channels on Safari

### ISSUE THREAD

**Issue by lloeki** [mattermost/platform#7241]
#### Summary

On Safari, switching channels produces a warning, prompting to check on the browser's console, which indeed shows various, changing errors.

#### Steps to reproduce

- not reproducible on Firefox 55.0.2
- not reproducible on Chrome 60.0.3112.101
- with Safari 11.0 (13604.1.38.1.3), login on either of:
  - pre-release.mattermost.com/core
  - platform 4.0.3 / omnibus-gitlab 9.4.5 (minus the developer mode warning)
- switch channels (possibly multiple times)

#### Expected behavior

No JS errors.

#### Observed behavior (that appears unintentional) 

![screen shot 2017-08-17 at 09 11 27](https://user-images.githubusercontent.com/75445/29400216-bd10e3b0-832c-11e7-947f-393ab277d346.png)

![screen shot 2017-08-17 at 09 09 24](https://user-images.githubusercontent.com/75445/29400212-b8578b26-832c-11e7-81f1-b401d8b342af.png)

**Comment by lfbrock** [comment]
Hi @lloeki - is this still reproducing on pre-release for you? 

We haven't been able to on Safari 11 (12604.1.38.1.3) which was the only version we could find to download, so wondering if you're still seeing it and if it's specific to the version you're using.

**Comment by lloeki** [comment]
Yep, reproduced on another machine.

Since you're mentioning a download, I reckon you're on 10.12 Sierra while I'm on 10.13 High Sierra 17A344b a.k.a public beta 5 (also guessing from the version number coincidentally starting with 12 and otherwise identical to mine which starts with 13).

**Comment by lfbrock** [comment]
That's probably it, I don't think we have anyone on our team on the beta builds - @lloeki would you be interested in submitting a fix for this?

**Comment by lindy65** [comment]
Hi @lloeki, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you'd like to submit a fix for this, we'd be happy to review the PR.

**Comment by lloeki** [comment]
@lindy65 @lfbrock Thanks for the heads up. 'm now on macOS 10.13 Beta (17A360a) with Safari Version 11.0 (13604.1.38.1.6) and the issue is still present. Sadly I am not in a position to be able to work on a fix for this :/
